version : '3'
services:
  projek_mppl:
    build: ./php
    image: projek_mppl_php:latest
    container_name: projek_mppl
    hostname: "projek_mppl"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - db_projek_mppl
  db_projek_mppl:
    image: mariadb:10.2
    container_name: db_projek_mppl
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djambred
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_projek_mppl
  nginx_projek_mppl:
    build: ./nginx
    image: nginx_projek_mppl:latest
    container_name: nginx_projek_mppl
    hostname: "nginx_projek_mppl"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - projek_mppl